### ISSUE TITLE
How do you cite this?

### ISSUE THREAD

**Issue by ntakouris** [davidstutz/latex-resources#3]

**Comment by davidstutz** [comment]
Good question. Unfortunately, most of the included examples are scattered across my publications and some of them actually correspond to templates from conferences/journals for which I do not deserve credit. However, if you still want to cite this repository, you can use

    @misc{Stutz2022,
      author = {David Stutz},
      title = {Collection of LaTeX resources and examples},
      publisher = {GitHub},
      journal = {GitHub repository},
      howpublished = {\url{https://github.com/davidstutz/latex-resources}},
      note = {Accessed on 18.05.2022}
    }
